### ISSUE TITLE
Add flood protection

### ISSUE THREAD

**Issue by wolfy1339** [hellomouse/Athena#20]
Around 7 lines burst and then 1 line per 0.7 seconds for freenode is good
At the same time, add a way to flush the queue even if the flood protection is disabled

**Comment by BWBellairs** [comment]
I was thinking we have the send queue being organised in terms of channels/targets so we can clear the queue for a specific channel/target or even prioritise important server data to be sent without that being cleared.

**Comment by wolfy1339** [comment]
Closed by #32
